name: CI/CD

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev

jobs:
  test-and-build-dev:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Specify the version of Node.js you're using

      - name: Install dependencies
        run: npm install --include=dev

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm run test

  deploy-push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --include=dev

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm run test

      - name: Deploy to server
        run: |
          # Add your deployment commands here
          # For example, you can use scp to copy files to a server or use a deployment tool
          echo "Deploying to server..."
